export {
  CONE_HEIGHT,
  CONE_SLOPE_ANGLE,
  CONE_WIDTH,
  PLANE_OFFSET_MAX,
  PLANE_OFFSET_MIN,
  acuteTiltFromHorizontal,
  analyzePlaneCut,
  classifyConic,
  clampPlaneOffset,
  conicLabel,
  distanceToNearestGenerator,
  generatorAngles,
  intersectPlaneWithEdge,
  isParallelToGenerator,
  matchesTarget,
  normalizePlaneAngle360,
  type PlaneCutAnalysis,
  type PlaneState,
} from './coneGeometry'
